unique_unsorted:	unique.c unsorted.c
	gcc -o unique_unsorted unique.c unsorted.c

parity_unsorted:	parity.c unsorted.c
	gcc -o parity_unsorted parity.c unsorted.c

unique_sorted:	unique.c sorted.c
	gcc -o unique_sorted unique.c sorted.c

parity_sorted:	parity.c sorted.c
	gcc -o parity_sorted parity.c sorted.c
